
export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST"
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS"
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL"


export const ALL_CONVERSATION_REQUEST = "ALL_CONVERSATION_REQUEST"
export const ALL_CONVERSATION_SUCCESS = "ALL_CONVERSATION_SUCCESS"
export const ALL_CONVERSATION_FAIL = "ALL_CONVERSATION_FAIL"

export const SINGLE_CONVERSATION_REQUEST = "SINGLE_CONVERSATION_REQUEST"
export const SINGLE_CONVERSATION_SUCCESS = "SINGLE_CONVERSATION_SUCCESS"
export const SINGLE_CONVERSATION_FAIL = "SINGLE_CONVERSATION_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS"